tables:
  # DBF to Oracle example
  dbf_to_oracle_table:
    source_type: dbf
    source_file_path: [sample1.dbf, sample2.dbf]  # Explicit DBF source file
    target_type: oracle
    target_table: TEST_DBF
    primary_key: []
    batch_size: 500
    drop_if_exists: true
    dbf_options: {}
    # Data quality checking configuration
    data_quality_checks:
      enable_row_count_check: true      # Enable row count validation
      enable_content_check: true        # Enable content accuracy validation
      sample_percentage: 10.0           # Percentage of rows to sample for content validation
      exclude_columns: ['U_ID', 'SOURCE_FILE']  # Columns to exclude from content comparison
      source_file_identifier: null     # Optional: identifier to filter target data for composite tables

  # DBF to Oracle example
  # dbf_to_xlsx_table:
  #   source_type: dbf
  #   source_file_path: sample.dbf  # Explicit DBF source file
  #   target_type: xlsx
  #   target_table: TEST_DBF
  #   target_file_path: TEST_DBF_XLSX.xlsx
  #   primary_key: []
  #   batch_size: 500
  #   drop_if_exists: true
  #   dbf_options: {}

  # CSV to Oracle example
  # csv_to_oracle_table:
  #   source_type: csv
  #   source_file_path: sample.csv  # Explicit CSV file path
  #   target_type: oracle
  #   target_table: TEST_CSV
  #   primary_key: [ID]
  #   batch_size: 1000
  #   drop_if_exists: true
  #   csv_options:
  #     infer_schema_length: 5000
  #     null_values: ['', 'NULL', 'N/A']
  #   # Data quality checking configuration
  #   data_quality_checks:
  #     enable_row_count_check: true      # Enable row count validation
  #     enable_content_check: true        # Enable content accuracy validation
  #     sample_percentage: 15.0           # Percentage of rows to sample for content validation
  #     exclude_columns: ['U_ID', 'SOURCE_FILE']  # Columns to exclude from content comparison
  #     source_file_identifier: 'sample.csv'     # Filter target data for this specific source file

  # XLSX to Oracle example
  # xlsx_to_oracle_table:
  #   source_type: xlsx
  #   source_file_path: sample.xlsx  # Explicit CSV file path
  #   target_type: oracle
  #   target_table: TEST_XLSX
  #   primary_key: [ID]
  #   batch_size: 1000
  #   drop_if_exists: true
  #   csv_options:
  #     infer_schema_length: 5000
  #     null_values: ['', 'NULL', 'N/A']
  
# Custom query combine xlsx
  # testiles_pipeline:
  #   source_type: custom_query
  #   custom_query: sql/custom_query.sql
  #   # Target Configuration
  #   target_type: xlsx
  #   target_table: TARGET_TABLE               # Always required
  #   target_file_path: data/combined.xlsx     # For file targets
  #   batch_size: 1000
  #   data_source:
  #     type: xlsx
  #     file_path: [data/sample1.xlsx, data/sample2.xlsx]
  #     table_alias: [sample1, sample2]

# Example: Customer query on csv
  # testiles_pipeline:
  #   source_type: custom_query
  #   custom_query: sql/custom_query.sql
  #   target_table: TESTILES
  #   batch_size: 1000
  #   primary_key: [ID]
  #   indexes:
  #     - name: idx_testiles
  #       columns: [NAME_NAME]
  #       unique: false
  #   data_source:
  #     type: csv
  #     file_path: data/testiles_pipeline.csv
  #     table_alias: testiles_pipeline
  #     options:
  #       separator: ","
  #       has_header: true

  # employees:
  #   source_type: csv
  #   target_table: EMPLOYEES
  #   batch_size: 1000
  #   primary_key: [employee_id]
  #   indexes:
  #     - name: idx_emp_email
  #       columns: [email]
  #       unique: true
  #   csv_options:
  #     separator: ","
  #     has_header: true

  # employee_summary:
  #   source_type: custom_query
  #   custom_query: sql/employee_summary.sql
  #   target_table: EMPLOYEE_SUMMARY
  #   batch_size: 500
  #   primary_key: [department_id]

  # departments:
  #   source_type: table
  #   source_table: DEPT
  #   source_schema: HR
  #   target_table: DEPARTMENTS_COPY
  #   foreign_keys:
  #     - columns: [manager_id]
  #       reference_table: EMPLOYEES
  #       reference_columns: [employee_id]